version: '3'

services:
  service1:
    build: .
    ports:
      - "3000:3000"
    environment: 
      - NAME=Service1
      - LINK=http://service2:3000/

  service2:
    build: .
    ports:
      - "3001:3000"
    environment: 
      - NAME=Service2
      - LINK=https://news.ycombinator.com/